### ISSUE TITLE
Upset succeeds on Mac and fails on ubuntu

### ISSUE THREAD

**Issue by NikosEfthias** [stainless-steel/sqlite3-sys#3]
How do I upgrade sqlite version the code is built against ?

**Comment by IvanUkhov** [comment]
It’s not here. It’s in the `sqlite3-src` package. You need to update the `source` directory there.

**Comment by IvanUkhov** [comment]
It might also be helpful to find our the difference between your setup and the one on Travis CI:

https://travis-ci.org/stainless-steel/sqlite3-src

https://travis-ci.org/stainless-steel/sqlite3-sys

**Comment by NikosEfthias** [comment]
code is built alright that's not the problem on runtime the sql syntax throws error from sqlite inside

**Comment by IvanUkhov** [comment]
If I’m not mistaken, we build version 3.28.0, which is the latest one at the moment.

**Comment by NikosEfthias** [comment]
3.28 supports upserts however in my case it works fine on arch linux and Mac but on ubuntu it gives syntax error for `on conflict` clause

**Comment by NikosEfthias** [comment]
so it doesn't seem to be the latest version

**Comment by IvanUkhov** [comment]
Try updating Cargo‘s cache via `cargo update`. It might be the case that you still have the old version.

**Comment by NikosEfthias** [comment]
im using a docker container to build the project so there's no cache every time it fetches the new packages

**Comment by IvanUkhov** [comment]
The OS distribution might have an older version installed, and it gets picked up. Try the `bundled` feature to prevent this from happening:

```rust
[dependencies.sqlite3-src]
version = "…"
features = ["bundled"]
```

**Comment by NikosEfthias** [comment]
thanks
